services:
  - type: web
    name: n8n-luis
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-luis-32ki.onrender.com
      - key: PORT
        value: 443
